# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # schedule:
  # - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      # Runs a single command using the runners shell
      - name: Install deps
        run: npm install

      # Runs a single command using the runners shell
      - name: Update sizes
        run: node ./nodeFetchSizes.js

      # Runs a set of commands using the runners shell
      - name: Commit sizes
        run: git add . && git commit --amend --no-edit

      - name: Deploy
        run: npm run deploy
